### PR TITLE
Merge man pages

### PR DESCRIPTION
**Pull request by ghost**
@johnraff, I wonder if it would be OK with you to merge the man pages into master and release.

The new branch supplies the system with man page versions of existing helpfiles and additional documentaiton in the man page format. I intend to write a couple of man pages for BL and update the package step by step.

### CODE REVIEW

**Comment by johnraff** [comment]
Just one question: shouldn't the man pages be packaged along with their associated commands?
ie in bunsen-utilities, bunsen-configs...

Also, note @capn-damo damo's edit to [helpfile-bl-alternatives.txt](https://github.com/BunsenLabs/bunsen-docs/commit/cf789ba52460126db44e007a79aff8cb4c73382c#diff-22dcad92b17bc171f68028efad2faff0) (remove leafpad from one line)

**Comment by ghost** [comment]
The idea was to have man pages in a human-readable format (markdown) and convert them at compile time into the groff format. Now, doing so would require adding a Makefile and an additional Build-Depends to every package shipping a man page. By sticking all of that into bunsen-docs, just one such alteration is necessary.

However, I would have nothing against just sticking real man pages (pre-compiled) into the respective packages and installing them using dh_installmanpages.

What would you prefer? Moving the man pages to the actual packages is a no-brainer and zero effort. Actually after thinking it over, I would prefer this kind of solution too.

**Comment by johnraff** [comment]
> However, I would have nothing against just sticking real man pages (pre-compiled) into the respective packages and installing them using dh_installmanpages.

So the markdown files go in bunsen-docs, and when the documentation is updated they get rebuilt, and the man files get copied into the various other packages? That sounds sensible. 

After all, a rewrite of the manuals will probably coincide with an update of the other helpfiles in bunsen-docs.

**Comment by johnraff** [comment]
Another btw: @capn-damo damo's rewrite of conkyzen &co. will mean a rewrite of the helpfiles too - at the very least replacing zenity with yad, and possibly other changes too.

**Comment by capn-damo** [comment]
> Another btw: @capn-damo damo's rewrite of conkyzen &co. will mean a rewrite of the helpfiles too - at the very least replacing zenity with yad, and possibly other changes too.

I've already done that in `bunsen-docs/ branch yadversion`

**Comment by johnraff** [comment]
Cheers!
@capn-damo could you post a list of the packages now with "yad" branches waiting to be merged?
Sorry if I've missed a previous posting.

**Comment by johnraff** [comment]
@2ion OK to merge this?

> Moving the man pages to the actual packages is a no-brainer and zero effort. Actually after thinking it over, I would prefer this kind of solution too.

The current content is consistent with that approach?

**Comment by ghost** [comment]
No.

I'll move the man pages (plus the Makefile) into a separate package, bunsen-manpage-sources which does not need to be installed and stuff the compiled man pages into the actual packages, mainly bunsen-utilities as for now.

**Comment by ghost** [comment]
Or wait. I'll take everything back and just add a Makefile plus man page sources to all packages which have man pages. This introduces the same Makefile into every package but is easier to manage. So I'll close this pull request for now.

I'll start with bunsen-os-release, my own package.

**Pull request closed without merging**
